### ISSUE TITLE
fb_rectangle.c MPixel

### ISSUE THREAD

**Issue by hhchung** [caramelli/fbmark#1]
Hi! This is a useful project for me, but I am a little confuse about the output information "MPixels/second" in the fb_rectangle.c (line 80). I think it should be Pixels instead of MPixel(megapixel)  or I just misunderstand the MPixel ? 

code https://github.com/caramelli/fbmark/blob/20569e2b62b41f429d0d1afce721717b70591777/fb_rectangle.c#L80

**Comment by caramelli** [comment]
I'm pleased that some people play with this code.

About the output, you have : count * w * h pixels during (end - start) ms
(as start = tv.tv_sec * 1000 + tv.tv_usec / 1000)
which represents : count * w * h pixels during [(end - start) * 1000] us
so : count * w * h megapixels per second

You have a screenshot on https://github.com/caramelli/dolsh/wiki/Framebuffer

Nicolas

**Comment by hhchung** [comment]
Oh, I realize the meaning.
Thank you for your elaborate explanation.
